interface Resources {
  "login": {
    "back": "Back",
    "checking": "Checking...",
    "confirm_password": "Confirm Password",
    "enter_id_label": "Enter your ID number",
    "forgot_password": "Forgot Password?",
    "good_to_see_you": "Good to see you",
    "loading": "Loading...",
    "logged_in_successfully": "Logged in successfully",
    "logging_in": "Logging in...",
    "login": "Login",
    "login_button": "Continue",
    "login_national_id_label": "Logging in as: {{id}}",
    "national_id_incorrect": "Invalid ID number. Please check and try again.",
    "national_id_missing": "ID number is missing. Please try again.",
    "new_password": "New Password",
    "no_account_found_redirecting": "No account found. Redirecting to sign up...",
    "otp_required": "Please enter the last 4 digits of the caller ID.",
    "otp_sent_message": "You will receive a phone call to {{phoneNumber}}. Please enter the last 4 digits of the caller ID below.",
    "otp_sent_message_no_phone": "You will receive a phone call. Please enter the last 4 digits of the caller ID below.",
    "otp_verified_successfully": "Verification code verified successfully",
    "password": "Password",
    "resend_code": "Call Again",
    "set_password": "Set Password",
    "setting_password": "Setting password...",
    "verification_code_label": "Last 4 Digits of Caller ID",
    "verify_code": "Verify Code",
    "verifying": "Verifying..."
  },
  "signup": {
    "account_created_successfully_pending_verification": "account_created_successfully_pending_verification",
    "back": "back",
    "delete_failed": "Delete failed",
    "form_data_missing": "Form data is missing",
    "otp_sent_message": "otp_sent_message",
    "otp_sent_message_no_phone": "otp_sent_message_no_phone",
    "password_required": "Password is required",
    "resend_code": "resend_code",
    "submit_application": "submit_application",
    "submitting": "submitting",
    "upload_failed": "Upload failed",
    "verification_code_label": "verification_code_label",
    "verification_code_sent_successfully": "verification_code_sent_successfully"
  },
  "translation": {
    "account_created_successfully_pending_verification": "account_created_successfully_pending_verification",
    "account_pending_message": "Your account is pending verification. You will be able to access all features once your account has been verified.",
    "account_pending_verification": "Account Pending Verification",
    "address_information": "address_information",
    "address_line2_required": "Address line 2 is required",
    "address_line2_too_long": "Address line 2 is too long",
    "address_line_two": "Address Line 2",
    "address_line_two_placeholder": "Apartment, suite, unit, building, floor, etc.",
    "all_day": "all_day",
    "applicant_details": "Applicant Details",
    "back": "Back",
    "beneficiary_logo_alt": "Beneficiary Portal Logo",
    "bug_content": "Content",
    "bug_title": "Title",
    "checking": "Checking...",
    "child_number_label": "Child {{number}}",
    "children_count_invalid": "Invalid number of children",
    "children_information": "Children Information",
    "children_mismatch": "Number of children does not match the details provided",
    "children_mismatch_hint": "The number of children entered does not match the children details provided.",
    "city": "City",
    "click_to_upload_or_drag_drop": "Click to upload or drag and drop",
    "confirm_new_password": "Confirm New Password",
    "confirm_password": "Confirm Password",
    "continue": "Continue",
    "create_password_message": "create_password_message",
    "create_post": "Create Post",
    "create_t3_turbo": "Congress Beneficiary Portal",
    "dashboard": "dashboard",
    "dashboard_welcome_message": "dashboard_welcome_message",
    "date_of_birth": "Date of Birth",
    "date_of_birth_required": "Date of birth is required",
    "delete_post": "Delete Post",
    "document_identity_appendix": "Identity Card Appendix",
    "document_identity_card": "Identity Card",
    "document_type_required": "Document type is required",
    "documents_optional_hint": "Identity documents are optional but recommended for faster verification.",
    "documents_required_hint": "Identity documents are required for account verification.",
    "email": "Email",
    "enter_national_id": "Enter National ID",
    "enter_new_password": "Enter New Password",
    "enter_password": "Enter Password",
    "enter_your_password": "Enter Your Password",
    "failed_to_check_account": "Failed to check account. Please try again.",
    "failed_to_create_post": "Failed to create post",
    "failed_to_delete_post": "Failed to delete post",
    "failed_to_send_otp": "Failed to initiate phone call. Please try again.",
    "failed_to_sign_in": "Failed to sign in. Please check your credentials and try again.",
    "family_status": "Family Status",
    "file_requirements": "Accepted file types: {{types}}. Maximum file size: {{maxSize}}",
    "file_size_too_large": "File size is too large. Maximum size: {{maxSize}}",
    "files_remaining": "{{remaining}} file(s) remaining",
    "first_name": "First Name",
    "forgot_password": "Forgot Password?",
    "form_data_missing": "Form data is missing. Please fill in all required fields.",
    "gov_appendix_link_text": "How to get your identity card appendix",
    "half_day": "half_day",
    "head_of_the_kollel_name": "head_of_the_kollel_name",
    "head_of_the_kollel_phone": "head_of_the_kollel_phone",
    "head_of_the_yeshiva_name_required": "Head of Yeshiva/Kollel name is required",
    "home_phone_number": "Home Phone Number",
    "house_number": "House Number",
    "house_number_required": "House number is required",
    "house_number_too_long": "House number is too long",
    "how_to_find_appendix": "How to find your identity card appendix",
    "identity_appendix_upload_id_required": "Identity appendix upload is required",
    "identity_card_upload_id_required": "Identity card upload is required",
    "identity_documents": "Identity Documents",
    "invalid_credentials": "Invalid credentials. Please check your ID number and password.",
    "invalid_date": "Invalid date",
    "invalid_file_type": "Invalid file type. Please upload a supported file format.",
    "invalid_phone_number": "Invalid phone number",
    "invalid_verification_code": "Invalid verification code. Please enter the last 4 digits of the caller ID.",
    "kollel": "kollel",
    "kollel_name": "kollel_name",
    "kollel_work_type": "kollel_work_type",
    "last_name": "Last Name",
    "loading": "Loading...",
    "logged_in_as": "Logged in as",
    "logged_in_successfully": "Logged in successfully",
    "logging_in": "Logging in...",
    "login": "Login",
    "logout": "Logout",
    "marital_status": "Marital Status",
    "name_required": "Name is required",
    "name_too_long": "Name is too long",
    "name_too_short": "Name is too short",
    "national_id": "National ID",
    "national_id_incorrect": "Invalid national ID",
    "new_password": "New Password",
    "no_cities_found": "No cities found",
    "no_posts_yet": "No posts yet",
    "no_streets_found": "No streets found",
    "notFound": "Page not found",
    "number_of_children": "Number of Children",
    "optional": "Optional",
    "organization_name": "Organization Name",
    "otp_invalid": "Invalid verification code",
    "otp_sent_message": "You will receive a phone call to {{phoneNumber}}. Please enter the last 4 digits of the caller ID below.",
    "otp_sent_message_no_phone": "You will receive a phone call. Please enter the last 4 digits of the caller ID below.",
    "password": "Password",
    "password_min_length": "Password must be at least 8 characters long",
    "password_too_long": "Password is too long",
    "password_too_short": "Password is too short (minimum 8 characters)",
    "passwords_do_not_match": "Passwords do not match",
    "personal_phone_number": "Personal Phone Number",
    "phone_number_optional": "Phone Number (Optional)",
    "phone_number_required": "Phone number is required",
    "please_enter_national_id": "Please enter your national ID",
    "please_enter_otp": "Please enter the last 4 digits of the caller ID",
    "please_enter_password": "Please enter your password",
    "post_list_is_disabled": "Post list is currently disabled",
    "postal_code": "Postal Code",
    "postal_code_required": "Postal code is required",
    "postal_code_too_long": "Postal code is too long",
    "postal_code_too_short": "Postal code is too short",
    "redirecting_to_login": "Redirecting to login...",
    "remove": "Remove",
    "resend_code": "Call Again",
    "reset_token_required": "Invalid reset link",
    "select_marital_status": "Select Marital Status",
    "sending_verification_code": "Initiating phone call...",
    "set_password": "Set Password",
    "set_your_password": "Set Your Password",
    "setting_password": "Setting password...",
    "sign_in": "Sign In",
    "sign_out": "Sign Out",
    "signing_in": "Signing in...",
    "signup_disclaimer": "By continuing, you agree to our terms and conditions.",
    "signup_subtitle": "Create your account to get started",
    "signup_title": "Sign Up",
    "spouse_details": "Spouse Details",
    "spouse_required": "Spouse details are required",
    "status_divorced": "Divorced",
    "status_married": "Married",
    "status_single": "Single",
    "street": "Street",
    "submit_application": "Submit Application",
    "submitting": "Submitting...",
    "tim_confirmation": "tim_confirmation",
    "upload_id_required": "Document upload is required",
    "verification_code": "Verification Code",
    "verification_code_label": "Last 4 Digits of Caller ID",
    "verification_code_sent_successfully": "verification_code_sent_successfully",
    "verify_code": "Verify Code",
    "verifying": "Verifying...",
    "yeshiva": "yeshiva",
    "yeshiva_details": "yeshiva_details",
    "yeshiva_name_required": "Yeshiva/Kollel name is required",
    "yeshiva_type": "yeshiva_type",
    "you_must_be_logged_in_to_delete_a_post": "You must be logged in to delete a post",
    "you_must_be_logged_in_to_post": "You must be logged in to create a post"
  }
}

export default Resources;
