/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthLayoutRouteImport } from './routes/_auth-layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as LoginComponentsSetPasswordStepRouteImport } from './routes/login/components/set-password-step'
import { Route as LoginComponentsPasswordStepRouteImport } from './routes/login/components/password-step'
import { Route as LoginComponentsIdentifyStepRouteImport } from './routes/login/components/identify-step'
import { Route as ApiOrpcSplatRouteImport } from './routes/api/orpc.$'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_auth-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const LoginComponentsSetPasswordStepRoute =
  LoginComponentsSetPasswordStepRouteImport.update({
    id: '/components/set-password-step',
    path: '/components/set-password-step',
    getParentRoute: () => LoginRoute,
  } as any)
const LoginComponentsPasswordStepRoute =
  LoginComponentsPasswordStepRouteImport.update({
    id: '/components/password-step',
    path: '/components/password-step',
    getParentRoute: () => LoginRoute,
  } as any)
const LoginComponentsIdentifyStepRoute =
  LoginComponentsIdentifyStepRouteImport.update({
    id: '/components/identify-step',
    path: '/components/identify-step',
    getParentRoute: () => LoginRoute,
  } as any)
const ApiOrpcSplatRoute = ApiOrpcSplatRouteImport.update({
  id: '/api/orpc/$',
  path: '/api/orpc/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRouteWithChildren
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/api/orpc/$': typeof ApiOrpcSplatRoute
  '/login/components/identify-step': typeof LoginComponentsIdentifyStepRoute
  '/login/components/password-step': typeof LoginComponentsPasswordStepRoute
  '/login/components/set-password-step': typeof LoginComponentsSetPasswordStepRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRouteWithChildren
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/api/orpc/$': typeof ApiOrpcSplatRoute
  '/login/components/identify-step': typeof LoginComponentsIdentifyStepRoute
  '/login/components/password-step': typeof LoginComponentsPasswordStepRoute
  '/login/components/set-password-step': typeof LoginComponentsSetPasswordStepRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth-layout': typeof AuthLayoutRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRouteWithChildren
  '/signup': typeof SignupRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/api/orpc/$': typeof ApiOrpcSplatRoute
  '/login/components/identify-step': typeof LoginComponentsIdentifyStepRoute
  '/login/components/password-step': typeof LoginComponentsPasswordStepRoute
  '/login/components/set-password-step': typeof LoginComponentsSetPasswordStepRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/api/orpc/$'
    | '/login/components/identify-step'
    | '/login/components/password-step'
    | '/login/components/set-password-step'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/api/orpc/$'
    | '/login/components/identify-step'
    | '/login/components/password-step'
    | '/login/components/set-password-step'
  id:
    | '__root__'
    | '/'
    | '/_auth-layout'
    | '/_authed'
    | '/login'
    | '/signup'
    | '/_authed/dashboard'
    | '/api/orpc/$'
    | '/login/components/identify-step'
    | '/login/components/password-step'
    | '/login/components/set-password-step'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLayoutRoute: typeof AuthLayoutRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRouteWithChildren
  SignupRoute: typeof SignupRoute
  ApiOrpcSplatRoute: typeof ApiOrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth-layout': {
      id: '/_auth-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/login/components/set-password-step': {
      id: '/login/components/set-password-step'
      path: '/components/set-password-step'
      fullPath: '/login/components/set-password-step'
      preLoaderRoute: typeof LoginComponentsSetPasswordStepRouteImport
      parentRoute: typeof LoginRoute
    }
    '/login/components/password-step': {
      id: '/login/components/password-step'
      path: '/components/password-step'
      fullPath: '/login/components/password-step'
      preLoaderRoute: typeof LoginComponentsPasswordStepRouteImport
      parentRoute: typeof LoginRoute
    }
    '/login/components/identify-step': {
      id: '/login/components/identify-step'
      path: '/components/identify-step'
      fullPath: '/login/components/identify-step'
      preLoaderRoute: typeof LoginComponentsIdentifyStepRouteImport
      parentRoute: typeof LoginRoute
    }
    '/api/orpc/$': {
      id: '/api/orpc/$'
      path: '/api/orpc/$'
      fullPath: '/api/orpc/$'
      preLoaderRoute: typeof ApiOrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface LoginRouteChildren {
  LoginComponentsIdentifyStepRoute: typeof LoginComponentsIdentifyStepRoute
  LoginComponentsPasswordStepRoute: typeof LoginComponentsPasswordStepRoute
  LoginComponentsSetPasswordStepRoute: typeof LoginComponentsSetPasswordStepRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginComponentsIdentifyStepRoute: LoginComponentsIdentifyStepRoute,
  LoginComponentsPasswordStepRoute: LoginComponentsPasswordStepRoute,
  LoginComponentsSetPasswordStepRoute: LoginComponentsSetPasswordStepRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLayoutRoute: AuthLayoutRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRouteWithChildren,
  SignupRoute: SignupRoute,
  ApiOrpcSplatRoute: ApiOrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
